import 'package:flutter/material.dart';
import '../models/sensor_report_model.dart';
import 'hydroponic_service.dart';

class SensorReportService {
  SensorReportService._();

  static List<WeeklySensorReport> getWeeklyReports(HydroponicService service) {
    // Data live hari ini jika terhubung ke sensor
    final liveTemp = service.hasData && service.waterTempValue > 0
        ? service.waterTempValue
        : 27.6;
    final livePh = service.hasData && service.phValue > 0
        ? service.phValue
        : 6.3;
    final liveTds = service.hasData && service.tdsValue > 0
        ? service.tdsValue
        : 615;
    final liveLevel = service.hasData && service.levelAirValue > 0
        ? service.levelAirValue
        : 82;

    return [
      // ===== MINGGU KE-4 (BERJALAN) =====
      WeeklySensorReport(
        id: 'week_4',
        weekLabel: 'Minggu Ke-4',
        dateRange: '15 Sep - 21 Sep 2026',
        statusBadge: service.isConnected ? 'Optimal • Live' : 'Optimal • 7 Hari',
        badgeColor: const Color(0xFF2E7D32),
        isCurrentWeek: true,
        dailyReports: [
          const DailySensorReport(
            dayName: 'Senin',
            dateStr: '15 Sep',
            temp: 27.2,
            ph: 6.3,
            tds: 605,
            waterLevel: 84,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Sirkulasi nutrisi lancar, tanaman selada fase vegetatif akhir.',
          ),
          const DailySensorReport(
            dayName: 'Selasa',
            dateStr: '16 Sep',
            temp: 27.8,
            ph: 6.4,
            tds: 620,
            waterLevel: 81,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Dosing otomatis AB Mix 15 detik berhasil stabil.',
          ),
          const DailySensorReport(
            dayName: 'Rabu',
            dateStr: '17 Sep',
            temp: 28.2,
            ph: 6.5,
            tds: 595,
            waterLevel: 78,
            condition: 'Normal',
            statusColor: Color(0xFF237497),
            note: 'Cuaca terik siang hari, kipas aerasi berjalan optimal.',
          ),
          const DailySensorReport(
            dayName: 'Kamis',
            dateStr: '18 Sep',
            temp: 27.4,
            ph: 6.2,
            tds: 630,
            waterLevel: 85,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Penambahan air baku 3 Liter ke tandon utama.',
          ),
          const DailySensorReport(
            dayName: 'Jumat',
            dateStr: '19 Sep',
            temp: 27.0,
            ph: 6.3,
            tds: 618,
            waterLevel: 83,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Pengecekan kebersihan talang NFT dan akar selada.',
          ),
          const DailySensorReport(
            dayName: 'Sabtu',
            dateStr: '20 Sep',
            temp: 27.7,
            ph: 6.4,
            tds: 612,
            waterLevel: 79,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Kalibrasi rutin elektroda sensor pH & TDS.',
          ),
          DailySensorReport(
            dayName: 'Minggu',
            dateStr: '21 Sep',
            temp: liveTemp,
            ph: livePh,
            tds: liveTds,
            waterLevel: liveLevel,
            condition: service.isConnected ? 'Optimal (Live)' : 'Optimal',
            statusColor: service.isConnected
                ? const Color(0xFF2E7D32)
                : const Color(0xFF237497),
            note: service.isConnected
                ? 'Terhubung realtime ke endpoint API sensor ESP32/Flask.'
                : 'Data pemantauan sensor hari ini tersimpan baik.',
            isLive: true,
          ),
        ],
      ),

      // ===== MINGGU KE-3 (TERARSIP) =====
      const WeeklySensorReport(
        id: 'week_3',
        weekLabel: 'Minggu Ke-3',
        dateRange: '08 Sep - 14 Sep 2026',
        statusBadge: 'Tuntas • 7 Hari',
        badgeColor: Color(0xFF237497),
        isCurrentWeek: false,
        dailyReports: [
          DailySensorReport(
            dayName: 'Senin',
            dateStr: '08 Sep',
            temp: 26.9,
            ph: 6.2,
            tds: 580,
            waterLevel: 88,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Penggantian larutan tandon awal minggu berjalan sukses.',
          ),
          DailySensorReport(
            dayName: 'Selasa',
            dateStr: '09 Sep',
            temp: 27.3,
            ph: 6.3,
            tds: 600,
            waterLevel: 85,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Dosing nutrisi penyesuaian target 600 ppm.',
          ),
          DailySensorReport(
            dayName: 'Rabu',
            dateStr: '10 Sep',
            temp: 27.8,
            ph: 6.4,
            tds: 605,
            waterLevel: 82,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Laju aliran air talang NFT 1.8 Liter/menit stabil.',
          ),
          DailySensorReport(
            dayName: 'Kamis',
            dateStr: '11 Sep',
            temp: 28.5,
            ph: 6.6,
            tds: 590,
            waterLevel: 76,
            condition: 'Waspada',
            statusColor: Color(0xFFD97706),
            note: 'Suhu tandon naik sesaat, sistem cooling aktif 20 menit.',
          ),
          DailySensorReport(
            dayName: 'Jumat',
            dateStr: '12 Sep',
            temp: 27.1,
            ph: 6.3,
            tds: 615,
            waterLevel: 84,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Penambahan air tandon 4L setelah pendinginan.',
          ),
          DailySensorReport(
            dayName: 'Sabtu',
            dateStr: '13 Sep',
            temp: 27.4,
            ph: 6.4,
            tds: 610,
            waterLevel: 80,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Inspeksi filter inlet pompa bebas lumut.',
          ),
          DailySensorReport(
            dayName: 'Minggu',
            dateStr: '14 Sep',
            temp: 27.2,
            ph: 6.3,
            tds: 608,
            waterLevel: 78,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Tutup laporan mingguan ke-3, performa rata-rata stabil.',
          ),
        ],
      ),

      // ===== MINGGU KE-2 (TERARSIP) =====
      const WeeklySensorReport(
        id: 'week_2',
        weekLabel: 'Minggu Ke-2',
        dateRange: '01 Sep - 07 Sep 2026',
        statusBadge: 'Tuntas • 7 Hari',
        badgeColor: Color(0xFF237497),
        isCurrentWeek: false,
        dailyReports: [
          DailySensorReport(
            dayName: 'Senin',
            dateStr: '01 Sep',
            temp: 26.8,
            ph: 6.1,
            tds: 550,
            waterLevel: 90,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Pindah tanam bibit ke modul instalasi hidroponik.',
          ),
          DailySensorReport(
            dayName: 'Selasa',
            dateStr: '02 Sep',
            temp: 27.0,
            ph: 6.2,
            tds: 560,
            waterLevel: 87,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Adaptasi bibit berjalan baik, akar mulai menyentuh aliran.',
          ),
          DailySensorReport(
            dayName: 'Rabu',
            dateStr: '03 Sep',
            temp: 27.5,
            ph: 6.3,
            tds: 575,
            waterLevel: 84,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Penyesuaian nutrisi awal vegetatif 570 ppm.',
          ),
          DailySensorReport(
            dayName: 'Kamis',
            dateStr: '04 Sep',
            temp: 27.6,
            ph: 6.4,
            tds: 580,
            waterLevel: 82,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Monitoring pencahayaan greenhouse dan kanopi.',
          ),
          DailySensorReport(
            dayName: 'Jumat',
            dateStr: '05 Sep',
            temp: 27.2,
            ph: 6.3,
            tds: 585,
            waterLevel: 80,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Daur sirkulasi pompa aerasi 24 jam non-stop.',
          ),
          DailySensorReport(
            dayName: 'Sabtu',
            dateStr: '06 Sep',
            temp: 27.3,
            ph: 6.3,
            tds: 590,
            waterLevel: 78,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Pengujian sensor ultrasonik air tandon 100% akurat.',
          ),
          DailySensorReport(
            dayName: 'Minggu',
            dateStr: '07 Sep',
            temp: 27.1,
            ph: 6.2,
            tds: 588,
            waterLevel: 76,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Evaluasi mingguan: pertumbuhan daun selada seragam.',
          ),
        ],
      ),

      // ===== MINGGU KE-1 (TERARSIP) =====
      const WeeklySensorReport(
        id: 'week_1',
        weekLabel: 'Minggu Ke-1',
        dateRange: '25 Agu - 31 Agu 2026',
        statusBadge: 'Tuntas • 7 Hari',
        badgeColor: Color(0xFF237497),
        isCurrentWeek: false,
        dailyReports: [
          DailySensorReport(
            dayName: 'Senin',
            dateStr: '25 Agu',
            temp: 26.5,
            ph: 6.5,
            tds: 480,
            waterLevel: 92,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Persiapan modul & sterilisasi bak penampungan.',
          ),
          DailySensorReport(
            dayName: 'Selasa',
            dateStr: '26 Agu',
            temp: 26.7,
            ph: 6.4,
            tds: 500,
            waterLevel: 90,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Pengisian air baku dan pencampuran nutrisi awal.',
          ),
          DailySensorReport(
            dayName: 'Rabu',
            dateStr: '27 Agu',
            temp: 27.0,
            ph: 6.3,
            tds: 520,
            waterLevel: 88,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Penyemaian rockwool selada butterhead.',
          ),
          DailySensorReport(
            dayName: 'Kamis',
            dateStr: '28 Agu',
            temp: 27.2,
            ph: 6.3,
            tds: 525,
            waterLevel: 86,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Benih mulai berkecambah (sprout) 98% serempak.',
          ),
          DailySensorReport(
            dayName: 'Jumat',
            dateStr: '29 Agu',
            temp: 26.9,
            ph: 6.2,
            tds: 530,
            waterLevel: 85,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Perkenalan sinar matahari pagi untuk semaian.',
          ),
          DailySensorReport(
            dayName: 'Sabtu',
            dateStr: '30 Agu',
            temp: 27.1,
            ph: 6.3,
            tds: 535,
            waterLevel: 83,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Pengecekan sensor suhu air tandon.',
          ),
          DailySensorReport(
            dayName: 'Minggu',
            dateStr: '31 Agu',
            temp: 27.0,
            ph: 6.2,
            tds: 540,
            waterLevel: 81,
            condition: 'Optimal',
            statusColor: Color(0xFF2E7D32),
            note: 'Semaian siap pindah tanam ke instalasi hidroponik.',
          ),
        ],
      ),
    ];
  }
}
